// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmlnM1Tggx9PE6na8lcSH1dJeAG4R23Q',
    appId: '1:883867452679:web:801b04e63820a59a4871a2',
    messagingSenderId: '883867452679',
    projectId: 'biblioteca-190bf',
    authDomain: 'biblioteca-190bf.firebaseapp.com',
    storageBucket: 'biblioteca-190bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuyeVY8cixdh4Gm5cDp4ryqn9jtGGBq8',
    appId: '1:883867452679:android:07c544d7c49fa8844871a2',
    messagingSenderId: '883867452679',
    projectId: 'biblioteca-190bf',
    storageBucket: 'biblioteca-190bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ZajrmPPWo6yhgjar2cTxY47eDCahe_g',
    appId: '1:883867452679:ios:1931dc8da53fbe6a4871a2',
    messagingSenderId: '883867452679',
    projectId: 'biblioteca-190bf',
    storageBucket: 'biblioteca-190bf.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ZajrmPPWo6yhgjar2cTxY47eDCahe_g',
    appId: '1:883867452679:ios:1931dc8da53fbe6a4871a2',
    messagingSenderId: '883867452679',
    projectId: 'biblioteca-190bf',
    storageBucket: 'biblioteca-190bf.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQmlnM1Tggx9PE6na8lcSH1dJeAG4R23Q',
    appId: '1:883867452679:web:984cb7d07b85faec4871a2',
    messagingSenderId: '883867452679',
    projectId: 'biblioteca-190bf',
    authDomain: 'biblioteca-190bf.firebaseapp.com',
    storageBucket: 'biblioteca-190bf.firebasestorage.app',
  );

}